# Get your free API key from: https://www.themoviedb.org/settings/api
# API Read Access Token (Bearer token)
API_KEY = "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

